app:
  web_hook_url: "https://example.com/webhook" # webhook地址，留空表示不使用webhook
  proxy_url: "socks5://127.0.0.1:7890"

http_serve: # 管理 bot 服务
  addr: ":8080" # API 服务器监听地址

database: # 数据库配置
  dsn: "root:@tcp(127.0.0.1:3306)/telegram?charset=utf8mb4&parseTime=True&loc=Local" # 数据库连接字符串
  timeout: 5s # 数据库连接超时时间
  max_open_conn: 10 # 数据库最大打开连接数
  max_idle_conn: 5 # 数据库最大空闲连接数
  max_life_time: 30m # 数据库连接最大生命周期
  max_idle_time: 10m # 数据库连接最大空闲时间

# 客服配置
customer: # 客服设置
  session_limit: 5000 # 单个群最多能同时5000个会话
  groups:
    - chat_id: -1003563520720
    # - chat_id: -1001234567890
    # - chat_id: -1009876543210

db: # KV存储配置
    path: "./data/user_topic.db"
    sync_on_write: false       # 不立即同步，提高性能
    sync_threshold: 100        # 100次操作后同步
    compact_delete_count: 1000 # 1000次删除后压缩
    compact_cooldown: 10       # 压缩冷却10秒
    sync_cooldown: 1           # 同步冷却1秒

# 业务 bot 配置
biz_bot:
  
